
# Necessary to avoid race conditions when testing packet capture/transmission on a machine
[env]
RUST_TEST_THREADS = "1"

[target.'cfg(unix)']
runner = "sudo -E"

[target.'cfg(windows)']
runner = "powershell -Command Start-Process -Verb runAs -FilePath"
